### PR TITLE
 fixed compatibility issue on Mac OS X (tested on Sierra)

### PR DESCRIPTION
**Pull request by ksudoh**
OSX-compatible memory-size stuffs have been included in src/lib/init.cc (it isn't cool enough but just works).
Now I've got a success on building nmtkit on OSX.

### CODE REVIEW

**Comment by odashi** [comment]
Are modified locations to DyNet libraries correct?

**Comment by ksudoh** [comment]
DyNet header files and libraries are installed on ${prefix}/include and ${prefix}/lib by "make install". Don't they match your policy?

**Comment by odashi** [comment]
[Official installation document](https://dynet.readthedocs.io/en/latest/install.html#compiling-linking-external-programs) uses the `build` directory directly and does not use `make install` command. It might be better to follow the policy of this document for now.

**Comment by ksudoh** [comment]
I completely missed that one. Thanks.

**Pull request merged**
